CFG = {
    "seq_len": 512,
    "num_cls": 3,
    "condition_mode": "joint",
    "condition_specs": {
        "stability": {
            "names": ["stability_class"],
            "classes": [["low", "medium", "high"]],
        },
        "topology": {
            "names": ["topology_label"],
            "classes": [["parallel", "hybrid", "antiparallel"]],
        },
        "joint": {
            "names": ["stability_class", "topology_label"],
            "classes": [["low", "medium", "high"], ["parallel", "hybrid", "antiparallel"]],
        },
    },
    "stability_low_tm": 50.0,
    "stability_high_tm": 65.0,
    "max_g4stab_std": 5.0,
    "split": 0.8,
    "val_split": 0.1,
    "lr": 5e-4,
    "check_val_every_n_epoch": 10,
    "metric_samples": 256,
    "g4hunter_window": 25,
    "checkpoint_save_top_k": 10,
    "lstm": dict(
        emb_dim=128,
        cond_dim=16,
        hidden_dim=768,
        num_layers=2,
        mlp_layers=1,
        dropout=0.3,
        sample_temperature=1.0,
        top_k=0,
    ),
    "vae": dict(
        hidden_dim=320,
        latent_dim=192,
        num_res_blocks=2,
        dropout=0.1,
        sample_temperature=0.8,
        beta=0.1,
        beta_warmup_steps=20000,
    ),
    "dfm": dict(
        hidden_dim=256,
        num_cnn_stacks=4,
        num_transformer_layers=1,
        num_attention_heads=4,
        transformer_ff_mult=1,
        dropout=0.0,
        alpha_max=8.0,
        alpha_scale=2.0,
        prior_pseudocount=2.0,
        num_integration_steps=100,
        flow_temp=1.0,
        classifier_free_guidance=True,
        cond_drop_prob=0.3,
        allow_nan_cfactor=True,
    ),
    "ddsm": dict(
        hidden_dim=256,
        num_layers=20,
        dropout=0.1,
        min_time=0.01,
        max_time=4.0,
        dirichlet_scale=24.0,
        score_clip=50.0,
        denoising_loss_weight=0.0,
        num_sampling_steps=100,
        sampling_noise=0.02,
        classifier_free_guidance=True,
        cond_drop_prob=0.3,
        noise_table_path=None,
        time_dependent_weights_path=None,
        use_official_noise=True,
        official_reverse_sampler=True,
        time_importance_sampling=True,
        random_order=False,
        speed_balanced=True,
    ),
}
